### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by allyjarjour** [benfox1216/Crate#16]
- [x] As a user, when I visit /crates the first time and click on the + subscribe button, I am taken to a /style-preferences page. 

- [x] As a user, I should see a style survey on the  /style-preferences page with a series of categories of clothing, reflecting each style,  to choose from.  

- [x] After I complete the form, I should see a summary of my style on the /style-preferences page.

**Comment by brian-greeson** [comment]
BE is done. Issues: #17 #7
